---
- name: Configureer Homelab Server
  hosts: homeserver
  become: yes
  gather_facts: yes

  roles:
    # 1. 🏗️ De Fundering (Eerst Docker, dan de rest)
    - role: common
    - role: security
    - role: fail2ban
    - role: docker

    # 2. 🛡️ De Poortwachter
    - role: duckdns
    - role: caddy
    - role: portainer

    # 3. 🔐 Applicaties & Data
    - role: vaultwarden
    - role: postgres
    - role: mosquitto

    # 4. 🔍 Hardware & Bridges
    - { role: zigbee2mqtt, when: "zigbee_device is defined" }
    - { role: zwavejsui,   when: "zwave_device is defined" }

    # 5. 🧠 Het Brein & Dashboards
    - role: homeassistant
    - role: esphome
    - role: flame

    # 6. 📂 Backups
    - role: rsync
    - role: rclone
