---
- name: Maak Caddy data mappen aan
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /opt/docker/caddy
    - /opt/docker/caddy/data
    - /opt/docker/caddy/config

- name: Kopieer Caddyfile template
  template:
    src: Caddyfile.j2
    dest: /opt/docker/caddy/Caddyfile
  notify: Restart Caddy

- name: Start Caddy container
  docker_container:
    name: caddy
    image: caddy:latest
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/caddy/data:/data
      - /opt/docker/caddy/config:/config
