---
- name: Maak directory voor Caddy mappen
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ docker_base_path }}/caddy"
    - "{{ docker_base_path }}/caddy/data"
    - "{{ docker_base_path }}/caddy/config"

- name: Plaats Caddyfile
  template:
    src: Caddyfile.j2
    dest: "{{ docker_base_path }}/caddy/Caddyfile"
    mode: '0644'

- name: Start Caddy container
  docker_container:
    name: caddy
    image: caddy:latest
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ docker_base_path }}/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "{{ docker_base_path }}/caddy/data:/data"
      - "{{ docker_base_path }}/caddy/config:/config"
