---
- name: Installeer UFW
  apt:
    name: ufw
    state: present

- name: Sta SSH toe (Cruciaal!)
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Sta Portainer toe (HTTPS)
  ufw:
    rule: allow
    port: '9443'
    proto: tcp

- name: Sta Flame Dashboard toe
  ufw:
    rule: allow
    port: '5005'
    proto: tcp

- name: Sta Zigbee2MQTT Frontend toe
  ufw:
    rule: allow
    port: '8080'
    proto: tcp

- name: Sta Home Assistant toe
  ufw:
    rule: allow
    port: '8123'
    proto: tcp

- name: Sta ESPHome Dashboard toe
  ufw:
    rule: allow
    port: '6052'
    proto: tcp

- name: Sta Z-Wave JS UI toe
  ufw:
    rule: allow
    port: '8091'
    proto: tcp

- name: Sta Matter Server toe
  ufw:
    rule: allow
    port: '5580'
    proto: tcp

- name: Sta MQTT toe (voor lokale sensoren/clients)
  ufw:
    rule: allow
    port: '1883'
    proto: tcp

- name: Sta HTTP toe (voor SSL verificatie)
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Sta HTTPS toe (voor je apps)
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Zet de firewall aan
  ufw:
    state: enabled
    policy: deny

- name: "Lynis: Installeer audit tool"
  package:
    name: lynis
    state: present

- name: "Lynis: Controleer of het rapportbestand al bestaat"
  stat:
    path: /var/log/lynis-report.dat
  register: lynis_report

- name: "Lynis: Draai de eerste systeem audit (dit duurt even)"
  command: lynis audit system --quick
  when: not lynis_report.stat.exists
  # We gebruiken --quick om te voorkomen dat hij op user-input wacht
