docker_base_path: "/opt/docker"
docker_network_name: "t2_network"
domain: "duckdns.org"
timezone: "Europe/Amsterdam"
zigbee_subdomain: "zigbee"
ha_subdomain: "homeassistant"
portainer_subdomain: "portainer"

# Systeem check instellingen
log_filter_exclude: "kex_exchange_identification|AnotherMessageToIgnore"
