---
- name: Maak directory voor ESPHome config
  file:
    path: "{{ docker_base_path }}/esphome"
    state: directory
    mode: '0755'

- name: Start ESPHome container
  docker_container:
    name: esphome
    image: "{{ image_esphome }}"
    restart_policy: unless-stopped
    state: started
    networks:
      - name: t2_network
    ports:
      - "6052:6052"
    privileged: true
    volumes:
      - "{{ docker_base_path }}/esphome:/config"
      - /etc/localtime:/etc/localtime:ro
    env:
      TZ: "{{ timezone }}"
