---
- name: Maak Zigbee2MQTT directory
  file:
    path: "{{ docker_base_path }}/zigbee2mqtt/data"
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'

- name: Plaats Zigbee2MQTT configuratie
  template:
    src: configuration.yaml.j2
    dest: "{{ docker_base_path }}/zigbee2mqtt/data/configuration.yaml"
    mode: '0644'

- name: VERWIJDER OUDE ZIGBEE (Forceer schone lei)
  docker_container:
    name: zigbee2mqtt
    state: absent

- name: START ZIGBEE2MQTT
  docker_container:
    name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    state: started
    restart_policy: always
    privileged: true
    # De poort-mapping die de 502 en de timeout heeft opgelost:
    ports:
      - "8080:8080"
    networks:
      - name: "t2_network"
    volumes:
      - "{{ docker_base_path }}/zigbee2mqtt/data:/app/data"
      - /run/udev:/run/udev:ro
    devices:
      - "{{ zigbee_device }}:/dev/ttyUSB0"
    env:
      TZ: "{{ timezone }}"
    recreate: yes

- name: Wacht tot de Zigbee2MQTT Frontend bereikbaar is (Poort 8080)
  wait_for:
    host: "{{ ansible_host }}"
    port: 8080
    delay: 10      # Geef de container tijd om de USB-stick te initialiseren
    timeout: 120   # Ruime marge voor database-migraties
    msg: "⚠️ Zigbee2MQTT frontend start traag of niet. Check: docker logs zigbee2mqtt"
