---
- name: Zorg dat het Docker netwerk bestaat
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: present

- name: Maak Vaultwarden data directory
  ansible.builtin.file:
    path: "/home/{{ main_user }}/vaultwarden"
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: '0755'

- name: Start Vaultwarden container
  community.docker.docker_container:
    name: vaultwarden
    image: "{{ image_vaultwarden }}"
    state: started
    restart_policy: always
    recreate: yes  # Forceert herstart met de nieuwe omgevingsvariabelen
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - "/home/{{ main_user }}/vaultwarden:/data"
    env:
      ADMIN_TOKEN: "{{ vaultwarden_admin_token }}"
      DOMAIN: "https://vault.{{ duckdns_domain }}.{{ domain }}"
      SIGNUPS_ALLOWED: "false"      # Blokkeert nieuwe registraties
      INVITATIONS_ALLOWED: "false"  # Blokkeert uitnodigingen voor extra veiligheid
