---
- name: Zorg dat het Docker netwerk bestaat
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: present

- name: Maak Vaultwarden data directory
  file:
    path: "/home/{{ main_user }}/vaultwarden"
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: '0755'

- name: Start Vaultwarden container
  community.docker.docker_container:
    name: vaultwarden
    image: "{{ image_vaultwarden }}"
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - "/home/{{ main_user }}/vaultwarden:/data"
    env:
      ADMIN_TOKEN: "{{ vaultwarden_admin_token }}"
      DOMAIN: "https://vault.{{ duckdns_domain }}.{{ domain }}"
