---
- name: PDF Genereren op Desktop van gebruiker
  shell: |
    "{{ ansible_python_interpreter }}" -m weasyprint /tmp/audit_{{ inventory_hostname.split('.')[0] }}.html ~/Desktop/Audit_{{ inventory_hostname.split('.')[0] }}_{{ ansible_date_time.date }}.pdf
  delegate_to: localhost
  register: pdf_result
  ignore_errors: yes

- name: Debug Output
  debug:
    msg: "Gebruikte Python: {{ ansible_python_interpreter }}"
  delegate_to: localhost
