---
- name: "HACS: Installatie"
  ansible.builtin.shell:
    cmd: "wget -O - https://get.hacs.xyz | bash -"
    chdir: "{{ ha_config_dir }}"
    creates: "{{ ha_config_dir }}/custom_components/hacs/manifest.json"

- name: "Haarlem Suite: Download Custom Components (Git)"
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ ha_config_dir }}/custom_components/{{ item.name }}"
  loop:
    - { name: 'p2000', repo: 'https://github.com/cyberjunky/home-assistant-p2000.git' }

- name: "Config: Hoofdconfiguratie via Template"
  ansible.builtin.template:
    src: configuration.yaml.j2
    dest: "{{ ha_config_dir }}/configuration.yaml"
    mode: '0644'
  notify: "Restart Home Assistant"

- name: "Automations: Push Volledige Haarlem Alerts"
  ansible.builtin.template:
    src: automations.yaml.j2
    dest: "{{ ha_config_dir }}/automations.yaml"
  notify: "Restart Home Assistant"
