---
- name: Maak directory voor Home Assistant configuratie
  file:
    path: "{{ docker_base_path }}/homeassistant"
    state: directory
    mode: '0755'

- name: Plaats Home Assistant configuratie
  template:
    src: configuration.yaml.j2
    dest: "{{ docker_base_path }}/homeassistant/configuration.yaml"
    mode: '0644'
    force: yes

- name: Start Home Assistant container
  docker_container:
    name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network_name }}"
    privileged: true
    volumes:
      - "{{ docker_base_path }}/homeassistant:/config"
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    env:
      TZ: "Europe/Amsterdam"
    published_ports:
      - "8123:8123"
