---
- name: Maak directory voor Postgres data
  file:
    path: "{{ docker_base_path }}/postgres/data"
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: '0755'

- name: Start PostgreSQL container
  docker_container:
    name: postgres_db
    image: postgres:16-alpine
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "5432:5432"
    volumes:
      - "{{ docker_base_path }}/postgres/data:/var/lib/postgresql/data"
    env:
      POSTGRES_USER: homeassistant
      POSTGRES_DB: homeassistant
      POSTGRES_PASSWORD: "{{ vault_postgres_password }}"
