# syntax: ansible-playbook -i inventory/hosts playbooks/install_all_hacs.yml --ask-vault-pass
---
- name: Installeer volledige lijst HACS Componenten
  hosts: all
  become: yes
  
  vars_files:
    - "../group_vars/all/secret.yml"

  vars:
    ha_config_dir: "/home/{{ ansible_user }}/homelab/homeassistant"

    hacs_integrations:
      - { name: "adaptive_lighting", repo: "basnijholt/adaptive-lighting" }
      - { name: "alarmo", repo: "nielsfaber/alarmo" }
      - { name: "battery_notes", repo: "andrew-codechimp/HA-Battery-Notes" }
      - { name: "energieprijzen", repo: "custom-components/nordpool" }
      - { name: "local_tuya", repo: "rospogrigio/localtuya" }
      - { name: "powercalc", repo: "bramstroker/homeassistant-powercalc" }
      - { name: "smartir", repo: "smartHomeHub/SmartIR" }
      - { name: "sonoff", repo: "AlexxIT/SonoffLAN" }
      - { name: "spook", repo: "frenck/spook" }

    hacs_frontend:
      - { name: "apexcharts-card", repo: "RomRider/apexcharts-card" }
      - { name: "auto-entities", repo: "thomasloven/lovelace-auto-entities" }
      - { name: "button-card", repo: "custom-cards/button-card" }
      - { name: "card-mod", repo: "thomasloven/lovelace-card-mod" }
      - { name: "clock-weather-card", repo: "pkissling/clock-weather-card" }
      - { name: "kiosk-mode", repo: "maykar/kiosk-mode" }
      - { name: "layout-card", repo: "thomasloven/lovelace-layout-card" }
      - { name: "mini-graph-card", repo: "kalkih/mini-graph-card" }
      - { name: "mini-media-player", repo: "kalkih/mini-media-player" }
      - { name: "multiple-entity-row", repo: "benct/lovelace-multiple-entity-row" }
      - { name: "mushroom", repo: "piitaya/lovelace-mushroom" }
      - { name: "paper-buttons-row", repo: "jcwillox/lovelace-paper-buttons-row" }
      - { name: "scheduler-card", repo: "nielsfaber/scheduler-card" }
      - { name: "slider-entity-row", repo: "thomasloven/lovelace-slider-entity-row" }
      - { name: "state-switch", repo: "thomasloven/lovelace-state-switch" }
      - { name: "vertical-stack-in-card", repo: "ofekashery/vertical-stack-in-card" }

  tasks:
    - name: Directories aanmaken
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      loop:
        - "{{ ha_config_dir }}/custom_components"
        - "{{ ha_config_dir }}/www"

    - name: Download Integraties
      ansible.builtin.git:
        repo: "https://{{ vault_github_token }}@github.com/{{ item.repo }}.git"
        dest: "{{ ha_config_dir }}/custom_components/{{ item.name }}"
        depth: 1
        force: yes
        version: HEAD
      loop: "{{ hacs_integrations }}"
      register: git_integrations

    - name: Download Frontend
      ansible.builtin.git:
        repo: "https://{{ vault_github_token }}@github.com/{{ item.repo }}.git"
        dest: "{{ ha_config_dir }}/www/{{ item.name }}"
        depth: 1
        force: yes
        version: HEAD
      loop: "{{ hacs_frontend }}"
      register: git_frontend

    - name: Herstart Home Assistant container
      community.docker.docker_container:
        name: homeassistant
        state: started
        restart: yes
      when: git_integrations.changed or git_frontend.changed
