# install_all_hacs.yml
---
- name: Installeer volledige lijst HACS Componenten
  hosts: all
  become: yes
  vars_files:
    - secret.yml
  vars:
    ha_config_dir: "/home/{{ ansible_user }}/homelab/homeassistant"

    # Alle Integraties (custom_components)
    hacs_integrations:
      - { name: "adaptive_lighting", repo: "basnijholt/adaptive-lighting" }
      - { name: "waste_collection_schedule", repo: "mampyllion/waste_collection_schedule" }
      - { name: "alarmo", repo: "nielsfaber/alarmo" }
      - { name: "automation_suggestions", repo: "aneisch/homeassistant-automation-suggestions" }
      - { name: "battery_notes", repo: "andrew-codechimp/HA-Battery-Notes" }
      - { name: "blitzortung", repo: "mr-vinn/home-assistant-blitzortung" }
      - { name: "buienradar", repo: "m_reuter/buienradar" }
      - { name: "dsmr_reader", repo: "custom-components/dsmr_reader" }
      - { name: "energieprijzen", repo: "custom-components/nordpool" }
      - { name: "gotify", repo: "ctiszen/hacs-gotify" }
      - { name: "knmi", repo: "wouterdevelder/knmi-home-assistant" }
      - { name: "local_tuya", repo: "rospogrigio/localtuya" }
      - { name: "pirate_weather", repo: "PirateWeather/pirateweather" }
      - { name: "powercalc", repo: "bramstroker/homeassistant-powercalc" }
      - { name: "rws_verkeer", repo: "pbrandao/hass_rws_verkeer" }
      - { name: "smartir", repo: "smartHomeHub/SmartIR" }
      - { name: "sonoff", repo: "AlexxIT/SonoffLAN" }
      - { name: "spook", repo: "frenck/spook" }
      - { name: "switch_manager", repo: "Sian-92/switch-manager" }
      - { name: "watchman", repo: "dext0rb/ha-watchman" }

    # Alle Frontend (www)
    hacs_frontend:
      - { name: "apexcharts-card", repo: "RomRider/apexcharts-card" }
      - { name: "atomic-calendar-revive", repo: "totaland/atomic-calendar-revive" }
      - { name: "auto-entities", repo: "thomasloven/lovelace-auto-entities" }
      - { name: "big-number-card", repo: "custom-cards/big-number-card" }
      - { name: "bubble-card", repo: "C_soft/bubble-card" }
      - { name: "button-card", repo: "custom-cards/button-card" }
      - { name: "card-mod", repo: "thomasloven/lovelace-card-mod" }
      - { name: "clock-weather-card", repo: "pkissling/clock-weather-card" }
      - { name: "decluttering-card", repo: "romrider/decluttering-card" }
      - { name: "google-home-theme", repo: "Lestat91/google-home-theme" }
      - { name: "swipe-navigation", repo: "maykar/hass-swipe-navigation" }
      - { name: "kiosk-mode", repo: "maykar/kiosk-mode" }
      - { name: "layout-card", repo: "thomasloven/lovelace-layout-card" }
      - { name: "mini-graph-card", repo: "kalkih/mini-graph-card" }
      - { name: "mini-media-player", repo: "kalkih/mini-media-player" }
      - { name: "multiple-entity-row", repo: "benct/lovelace-multiple-entity-row" }
      - { name: "mushroom", repo: "piitaya/lovelace-mushroom" }
      - { name: "paper-buttons-row", repo: "jcwillox/lovelace-paper-buttons-row" }
      - { name: "scheduler-card", repo: "nielsfaber/scheduler-card" }
      - { name: "slider-entity-row", repo: "thomasloven/lovelace-slider-entity-row" }
      - { name: "state-switch", repo: "thomasloven/lovelace-state-switch" }
      - { name: "vertical-stack-in-card", repo: "ofekashery/vertical-stack-in-card" }
      - { name: "weather-card-chart", repo: "Yevgenium/weather-card-chart" }

  tasks:
    - name: Directories aanmaken
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      loop:
        - "{{ ha_config_dir }}/custom_components"
        - "{{ ha_config_dir }}/www"

    - name: Download Integraties
      ansible.builtin.git:
        repo: "https://{{ vault_github_token }}@github.com/{{ item.repo }}.git"
        dest: "{{ ha_config_dir }}/custom_components/{{ item.name }}"
        depth: 1
        force: yes
      loop: "{{ hacs_integrations }}"
      register: git_integrations

    - name: Download Frontend
      ansible.builtin.git:
        repo: "https://{{ vault_github_token }}@github.com/{{ item.repo }}.git"
        dest: "{{ ha_config_dir }}/www/{{ item.name }}"
        depth: 1
        force: yes
      loop: "{{ hacs_frontend }}"

    - name: Herstart HA
      community.docker.docker_container:
        name: homeassistant
        state: restarted
      when: git_integrations.changed
