---
- name: Installeer Rsync
  apt:
    name: rsync
    state: present

- name: Maak directory voor lokale Rsync snapshots
  file:
    path: /opt/backups/rsync
    state: directory
    mode: '0700'
    owner: henry

- name: Plaats het lokale backup script
  template:
    src: local_backup.sh.j2
    dest: /usr/local/bin/local_backup.sh
    mode: '0755'

- name: Cronjob voor lokale backup (elke nacht om 03:00)
  cron:
    name: "Lokaal Rsync snapshot"
    hour: "03"
    minute: "00"
    job: "/usr/local/bin/local_backup.sh > /dev/null 2>&1"
